const productos =   [{id: 1, nombre: "AGENDA PRIMAVERAL", precio: 3000, categoria: "AGENDA", stock: 2}, 
                    {id: 2, nombre: "AGENDA MARIPOSAS", precio: 3200, categoria: "AGENDA", stock: 0},
                    {id: 3, nombre:  "AGENDA ZORRO", precio: 3150, categoria: "AGENDA", stock: 3},
                    {id: 4, nombre: "CALENDARIO COCODRILO", precio: 5200, categoria: "CALENDARIO", stock: 4},
                    {id: 5, nombre: "CALENDARIO CIERVO", precio:5200, categoria: "CALENDARIO",  stock: 10},
                    {id: 6, nombre: "CALENDARIO PEZ", precio: 5200, categoria: "CALENDARIO",  stock: 7},
                    {id: 7, nombre: "TAZA PRIMAVERAL", precio: 1200, categoria: "TAZA",  stock: 11},
                    {id: 8, nombre: "TAZA ZORRO", precio: 1200, categoria: "TAZA", stock: 0},
                    {id: 9, nombre: "TAZA FLAMENCO", precio: 1200, categoria: "TAZA",  stock: 8},
                    {id: 10, nombre: "CUADRO MEDUSAS", precio: 6500, categoria: "CUADRO",  stock: 0},
                    {id: 11, nombre: "CUADRO BOSQUE", precio: 6500, categoria: "CUADRO", stock: 9},
                    {id: 12, nombre: "CUADRO CASA", precio: 6500, categoria: "CUADRO",  stock: 4},
                    {id: 13, nombre: "ARTBAG RANA", precio: 4200, categoria: "ARTBAG",  stock: 11},
                    {id: 14, nombre: "ARTBAG TUCAN", precio: 4200, categoria: "ARTBAG",  stock: 0},
                    {id: 15, nombre: "ARTBAG CHICA PRIMAVERAL", precio: 4200, categoria: "ARTBAG",  stock: 7},
                    {id: 16, nombre: "ARTBAG ZORRO", precio: 4200, categoria: "ARTBAG",  stock: 9}]